### ISSUE TITLE
DINO

### ISSUE THREAD

**Issue by FilipAndersson245** [lucidrains/vit-pytorch#106]
Yannic just released an interesting video about [DINO](https://www.youtube.com/watch?v=h3ij3F3cPIk) that seem to produce great results in self-supervised learning
Is it feasible to suggest this be added here?

https://arxiv.org/abs/2104.14294
https://ai.facebook.com/blog/dino-paws-computer-vision-with-self-supervised-transformers-and-10x-more-efficient-training

**Comment by lucidrains** [comment]
@FilipAndersson245 sure! i could add it - but just so you know, Facebook AI also released a library (I usually only write a library if the author hasn't released the code yet and I get impatient)

**Comment by lucidrains** [comment]
Actually I'll just build it, it's a really important paper :)

**Comment by lucidrains** [comment]
@FilipAndersson245 I did a first-pass reimplemention of Dino in 0.18.0 https://github.com/lucidrains/vit-pytorch#dino let me know if that looks good to you!
