### ISSUE TITLE
Allow mpp to use non square patches

### ISSUE THREAD

**Issue by FilipAndersson245** [lucidrains/vit-pytorch#112]
Im examining a problem in my master thesis and thought our professors thought applying self-supervised learning. So my question is if it would be possible to use mpp with very unsquare patches (ours being 10x1)

Additionally is there anyhkng specifuc that would disallow us to use mpp on non image data?

**Comment by bigMaxM** [comment]
Hi @FilipAndersson245, I also face the same problems. Can I ask how you user non-square patches?

**Comment by FilipAndersson245** [comment]
Sorry I don't  have the code i changed or can recall what i changed.

**Comment by bigMaxM** [comment]
I have found the solution. Anyway, thanks for your reply!
