### ISSUE TITLE
Class token in CvT?

### ISSUE THREAD

**Issue by helia95** [lucidrains/vit-pytorch#115]
Hi, thanks for your amazing work! 
I have a question about CvT, to me it seems that there is no class token added before stage 3 but the features are averaged and passed directly to the classifier. Am I wrong?

**Comment by lucidrains** [comment]
@helia95 hey yes! now that you bring it up, I noticed I didn't add the classification token - however, this conflicts with the convolutional projections of queries (and the strided key / values), so I'm not sure how to approach it. it's not possible to append the one classification token to a square feature map

**Comment by lucidrains** [comment]
@helia95 honestly, after reading a bunch of papers, i don't think it'll matter much if it were CLS tokens or average pooled 😆 its just an interesting inconsistency in the paper
