### ISSUE TITLE
ask help: what's the meaning of self.to_latent = nn.Identity() in vit.py

### ISSUE THREAD

**Issue by rocke2020** [lucidrains/vit-pytorch#119]
Dear friends:

in  vit.py it seems the self.to_latent has no use, why use it? could you give instructions? thank!!!
1, in __init__()
self.to_latent = nn.Identity()
2,  in forward()
        x = self.to_latent(x)
        return self.mlp_head(x)

**Comment by chandan5362** [comment]
@rocke2020 , I guess it's basically the latent mapping of feature embeddings, e.i all the output feature vectors from each transformer layers are being concatenated together.

**Comment by AlbertiPot** [comment]
The same question, the class tokens are the same before and after the Identity in values and shape(that is what identity for).
