### ISSUE TITLE
how to get train.zip.

### ISSUE THREAD

**Issue by GitGhidorah** [lucidrains/vit-pytorch#13]
Hello!
Im beginner.
Please tell me how to get train.zip.

**Comment by lucidrains** [comment]
@GitGhidorah use torchvision's datasets https://pytorch.org/docs/stable/torchvision/datasets.html

**Comment by monajalal** [comment]
@lucidrains could you please share the dataset? The link doesn't exist anymore

![Screen Shot 2022-01-21 at 5 09 43 PM](https://user-images.githubusercontent.com/1892917/150606824-a927f073-f527-4bc1-9ac6-1b0254dd173d.png)

I need it for the 9th cell here
https://github.com/lucidrains/vit-pytorch/blob/main/examples/cats_and_dogs.ipynb

**Comment by monajalal** [comment]
Found something with the same train/test number at kaggle https://www.kaggle.com/alpaca0984/dog-vs-cat-with-pytorch/data?select=train.zip
