### ISSUE TITLE
swin transformer is very good in its paper,does vit-pytorch  has it?

### ISSUE THREAD

**Issue by henbucuoshanghai** [lucidrains/vit-pytorch#132]

**Comment by lucidrains** [comment]
@henbucuoshanghai it doesn't have it, since Swin already has a nice pytorch repository https://github.com/microsoft/Swin-Transformer

**Comment by henbucuoshanghai** [comment]
ok   tks   

the vit.py  has no decoder????is it right?  the official paper only has encoder? has no decoder?
