### ISSUE TITLE
the vit.py    position embedding   is not  sin and cos?

### ISSUE THREAD

**Issue by henbucuoshanghai** [lucidrains/vit-pytorch#134]
self.pos_embedding = nn.Parameter(torch.randn(1, num_patches + 1, dim))

the pos_enbedding is right??????  i dont understand   why    nn.Parameter     is here?

   the original transfomer is sin  and cos  ?

**Comment by AnimationFan** [comment]
the position embedding can be replaced by a group of learnable parameters, both ways works.
