### ISSUE TITLE
Redundant attention(transformer) used in T2T-ViT's `to-patch-embedding'

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/vit-pytorch#139]
Hi, Phil

I'm reading the T2T-ViT paper and find one place that might mismatch with the original paper.
https://github.com/lucidrains/vit-pytorch/blob/e5324242be61bcbf433e129e914aa4b4fa1a79a0/vit_pytorch/t2t.py#L35-L45

In the original paper, they use two iterations to reduce the token's length thus exists 3 split-operations ( corresponding kernels and strides are exactly the same with your code). But after the 3rd soft-split, the original paper doesn't follow any attention module but in your code, it still connects with a 3rd attention module.  I wonder maybe we can set a `is_final` flag to avoid adding the 3-rd attention module.

Maybe you can compare with the official: https://github.com/yitu-opensource/T2T-ViT/blob/88afb7cf30b603703c02b6e29c06be23c49cf6a2/models/t2t_vit.py#L82-L101

Best Regards

**Comment by CiaoHe** [comment]
The overall arch from the original paper:

![截屏2021-08-13 下午3 15 54](https://user-images.githubusercontent.com/39040787/129319275-65ed1b81-0519-4b01-a764-3099cf058fa0.png)

**Comment by lucidrains** [comment]
@CiaoHe thank you! i believe you are right! https://github.com/lucidrains/vit-pytorch/releases/tag/0.20.4
