### ISSUE TITLE
Should init scale matrix as diagonal form?

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/vit-pytorch#141]
Hi, Phil:

I noticed the LayerScale part in the `CaiT`, in the original paper the scale matrix is a diagonal form `(b,d,d)`, but in this implement, it just initialized in a form of vector(maybe can broadcast afterwards, but would it be better just initialize as a diagonal form?)
https://github.com/lucidrains/vit-pytorch/blob/3f754956fbfb1f97ae4f1e244a7ecb16eab79296/vit_pytorch/cait.py#L41

Best,

**Comment by lucidrains** [comment]
@CiaoHe hmm, are you sure it isn't equivalent? i thought this was exactly like rezero except with a parameter for each channel

do you want to try submitting a pull request to show your thoughts in code?

**Comment by CiaoHe** [comment]
Oh, my. I checked again, yes it's equivalent unless setting specific parameters for each channel. Sorry for my poor algebra...

**Comment by lucidrains** [comment]
@CiaoHe no worries, keep the bugs coming :)
