### ISSUE TITLE
Using `torch.nn.Hardswish()' instead of GELU()

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/vit-pytorch#142]
Hi Phil:
I noticed the original LeViT paper emphasizes using `torch.nn.Hardswish()` instead of GELU() as activation to save time. Plz have a check
https://github.com/lucidrains/vit-pytorch/blob/3f754956fbfb1f97ae4f1e244a7ecb16eab79296/vit_pytorch/levit.py#L32

**Comment by lucidrains** [comment]
:pray: ok, i updated it in 0.20.5!
