### ISSUE TITLE
ViT for generating embeddings only?

### ISSUE THREAD

**Issue by RobertHua96** [lucidrains/vit-pytorch#156]
Hi there, I notice all the examples are for a classification task - what areas of the code should I look at if I only want a ViT to extract features of images for me, and only produce an embedding for another model to use?

**Comment by lucidrains** [comment]
@RobertHua96 you can add a hook to the `to_latent` module to get the embedding https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/vit.py#L123 or just modify the class to return the embedding early (without passing it to `mlp_head`)
