### ISSUE TITLE
Would it better swap the `masked_tokens` and `unmasked_tokens`?

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/vit-pytorch#171]
Hi Phil:

I wonder whether here would it be better to swap the `decoder_tokens ` and `masked_tokens`? 
https://github.com/lucidrains/vit-pytorch/blob/5ae555750f60c6d5f87109027861aff2d0b2c74e/vit_pytorch/mae.py#L81

Since in Line55, the first part is masked_tokens and the second part is unmasked
https://github.com/lucidrains/vit-pytorch/blob/5ae555750f60c6d5f87109027861aff2d0b2c74e/vit_pytorch/mae.py#L55

**Comment by lucidrains** [comment]
@CiaoHe hello! 👋  sounds good, i made the change! https://github.com/lucidrains/vit-pytorch/commit/9f8c60651da992b13355dc5fe43333e6d6bada8b
