### ISSUE TITLE
PiT doesn't have a channel argument

### ISSUE THREAD

**Issue by torridgristle** [lucidrains/vit-pytorch#172]
Tryna use PiT set to 1 channel for the input images, but it's an unexpected keyboard argument. https://github.com/lucidrains/vit-pytorch/blob/d35345df6aa3973f8ab38b9a2dc2583d2b2b2d99/vit_pytorch/pit.py#L139 Ought to here I reckon.

**Comment by lucidrains** [comment]
@torridgristle sure, done https://github.com/lucidrains/vit-pytorch/commit/ff44d97cb0ce222bd9ad86563f9c0d83f660590c
