### ISSUE TITLE
batch_index_select for `x`, the `dim` should be set as 2?

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/vit-pytorch#177]
Hi Phil:

I read the ats and found one place that confuses me. Here, you use the `sampled_token_ids`(shape: B,h,k) to filter out old x(shape:B,h,N,d) and get the new x (shape: B,h,k,d). So, I wonder the dim should be set as 2 instead `dim=1`?
https://github.com/lucidrains/vit-pytorch/blob/f4b0b1409478626f80bbd253c6e2d2de3eb24fc2/vit_pytorch/ats_vit.py#L208

Best,

**Comment by lucidrains** [comment]
@CiaoHe 👋 hi again! so I think it should be 1 there, since we are outside the multi head attention class and are dealing with the original tokens, which is (batch, seq, dimension) without heads
