### ISSUE TITLE
Any chance to have conda installation?

### ISSUE THREAD

**Issue by yliu7366** [lucidrains/vit-pytorch#178]
Hi, I would like to utilize vit-pytorch but my cluster only accepts conda virtual environment. By any chance you will make vit-pytorch conda installation available?

**Comment by lucidrains** [comment]
@yliu7366 hey, i've never done it before, but i could look into it!

**Comment by lucidrains** [comment]
@yliu7366 Hi YanLing, i've submitted the recipe to conda-forge https://github.com/conda-forge/staged-recipes/pull/17329

**Comment by lucidrains** [comment]
https://anaconda.org/conda-forge/vit-pytorch
