### ISSUE TITLE
Vit MAE decoder positional embeddings

### ISSUE THREAD

**Issue by jrounds** [lucidrains/vit-pytorch#189]
Hi,

Thanks for ViT MAE.  Really accelerated my ideas on using it.  I forked your MAE file and I have been playing around with it, and one of the things I noticed is that for non-masked inputs the MAE decoder relies on the encoder essentially doing the decoder positional embedding op as part of the encoding output into the encoder to decoder linear transform.   

https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/mae.py#L68-L82

For example, 
line 68 has output of shape (batch, patches, encoding_dim)
line 72 turns it into (batch, patches, decoder dim) with a linear transformation, but note another version of line 72 might have been
```python
decoder_tokens = self.enc_to_dec(encoded_tokens) + self.decoder_pos_emb(unmasked_indices)  # different choice for line 72
```
That would have been a different choice, and it would have left the encoder insulated for the decoder_pos_emb. What that would have done (Imo) is make the encoder output more interpretable as contextual information.  At the moment, the encoder output is extremely delicate to probe by hand because it needs to be such that enc_to_dec transforms into both a meaningful contextual vector + meaningful decoder_pos_emb

These are changes I can explore on my own for impact on my own, but I came here to see if there were thoughts on insulating the encoder from learning decoder pos emd, and maybe if it was intentional to have line 72 through 82 not apply decoder_pos_emd to non-masked inputs.

**Comment by lucidrains** [comment]
@jrounds hey! it wasn't clear in the paper, so decided to just add it and let you experiment away https://github.com/lucidrains/vit-pytorch/commit/0082301f9e7c99758eff434472407e8cb30db5f5 do let me know what you end up discovering!

**Comment by lucidrains** [comment]
@jrounds hey, just got confirmation from Lucas Beyer himself that it needs to be reapplied, turned on by default now!
