### ISSUE TITLE
Finetune pretrained model for classfication

### ISSUE THREAD

**Issue by ajesujoba** [lucidrains/vit-pytorch#19]
To finetune the already pre-trained self-supervised model, do I use the snippet below?
```
import torch.nn as nn
checkpoint = torch.load('./pretrained-net.pt')
model2 = model.load_state_dict(checkpoint)
model.output =  nn.Linear(2048, 1000) #Do I need to add this? since the output layer was already given the vit model
```

**Comment by lucidrains** [comment]
@ajesujoba the pre-trained model isn't available yet. the code you see at https://github.com/lucidrains/vit-pytorch#self-supervised-training is just an example of how you can pre-train your own

**Comment by ajesujoba** [comment]
Thanks for your response. I have pretrained  a model. Thought I could fine tune with the code here as well.

**Comment by Hexinx** [comment]
>Is it convenient for you to release your pretrained model?
