### ISSUE TITLE
NesT implementation doesn't match the author/timm implementation

### ISSUE THREAD

**Issue by MarkYangjiayi** [lucidrains/vit-pytorch#192]
Hi, I was looking at the NesT implementation recently, and I have some doubts in your code. If you look at this [line](https://github.com/lucidrains/vit-pytorch/blob/1cc0f182a6093b03f58418c9d0914bafd7f150ad/vit_pytorch/nest.py#L133):
```
hierarchies = list(reversed(range(num_hierarchies)))
mults = [2 ** i for i in hierarchies]
layer_dims = list(map(lambda t: t * dim, mults))
```
If we assume `dim=96`, we will get a layer_dims of `[384, 192, 96]`. We also have a default block repeat of (8, 4, 1). Doing some simple computations, we will find that the feature size is too large in the first hierarchy.

If you look at the author's [original implementation](https://github.com/google-research/nested-transformer/blob/main/models/nest_net.py) or [pytorch-image-models](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/nest.py), you will find that their way of implementing is having the parameters the way it is, which is `[96, 192, 384]` and `[2, 2, 8]`.

The problem with your implementation is that the feature size explodes in the first few layers in the network(because we have more tokens in the layers near input), and GPU would quickly run out of memory.

It seems that we have a different understanding of which layer is the first layer. Can you please elaborate a little on why you implemented with a reversed setting?

**Comment by lucidrains** [comment]
@MarkYangjiayi oh darn, thank you Mark for catching this! can you let me know if https://github.com/lucidrains/vit-pytorch/commit/c1528acd46fddcf02955f1922f594c3bb713ef16 resolves the issue?

**Comment by MarkYangjiayi** [comment]
@lucidrains Yep, thanks for fixing. But you might also want to change the README [here](https://github.com/lucidrains/vit-pytorch/blob/main/README.md?plain=1#L545), the block repeats more in the deeper layer, (2, 2, 8) in the case of NesT-T.

Acctualy I think this problem was because there was a mistake in the Table A1 of the paper. There was a discussion([link](https://github.com/google-research/nested-transformer/issues/2)) in the repo of the original implementation. But the statement in the discussion is also not totally accurate, they just flipped the `multi` but forgot to flip `block_repeats`. But I think their implementation is correct now.

The core idea here is to have less parameters and repeating in earlier layers since the feature map is huge I think. Similar to conv nets where the channels gets deeper when feature maps sizes are reduced by pooling.

**Comment by lucidrains** [comment]
@MarkYangjiayi done! :pray: https://github.com/lucidrains/vit-pytorch/commit/126d204ff255b5e66880600b0151a79d2a293943
