### ISSUE TITLE
[BUG] efficient ViT does not support rectangular images

### ISSUE THREAD

**Issue by gdevos010** [lucidrains/vit-pytorch#197]
efficient model requires square images. I believe this can be updated to match the vit.py implementation 

https://github.com/lucidrains/vit-pytorch/blob/64a07f50e608350a01d257b78d29b64d2fce88fd/vit_pytorch/efficient.py#L7-L21

**Comment by lucidrains** [comment]
@gdevos010 Hi Greg!

while would recommend some of the proven alternatives, here you go!

```python
import torch
from vit_pytorch.efficient import ViT
from nystrom_attention import Nystromformer

efficient_transformer = Nystromformer(
    dim = 512,
    depth = 12,
    heads = 8,
    num_landmarks = 256
)

v = ViT(
    dim = 512,
    image_size = (1024, 2048),
    patch_size = 32,
    num_classes = 1000,
    transformer = efficient_transformer
)

img = torch.randn(1, 3, 1024, 2048) # your high resolution picture
v(img) # (1, 1000)
```

**Comment by gdevos010** [comment]
Thanks, Phil! Big fan of your work.

Im working through some ideas in my head
