### ISSUE TITLE
Using masks as preprocessing for classification [FR]

### ISSUE THREAD

**Issue by Tato14** [lucidrains/vit-pytorch#2]
Maybe it's a little bit too early to ask for this but could it be possible to specify regions within an image for `ViT` to perfom the prediction? I was thinking on a binary mask, for example, which could be used for the tiling step in order to obtain different images sequences. 

I am thinking on a pipeline where, in order to increase resolution, you could specify the regions to perform the training based on whatever reason you find it suitable (previous attention maps for example :smile:).

**Comment by lucidrains** [comment]
hmm, may be outside the scope of this package, and I want to stick with the simplicity, as it may hold educational value for CV folks

what were you thinking? some sort of recurrent hard attention architecture on top of the attention network?

**Comment by Tato14** [comment]
I am not sure if you ask *how* this should be implemented. If this is the case, I was thinking on some sort of preprocessing step that forces the tiling to specific regions. 

The *why* of this is related with some work I saw in the PANDA kaggle challenge (https://www.kaggle.com/c/prostate-cancer-grade-assessment/discussion/169108#940504) where the authors use an attention pooling layer to select specific regions and increase the resolution of the images they could process for prediction. I guess that ViT could be used for this in a iterative way. Starting from low resolution > generate maps > tiling on medium resolution >...

I understand the of topic, don't worry. In any case, if you think it could be somehow interesting and could help me with this it would be really great!

**Comment by lucidrains** [comment]
@Tato14 Ahh, I understand your problem. Very much related to https://arxiv.org/abs/1905.03711 and I believe it will work, but outside the scope of this repository.

**Comment by lucidrains** [comment]
@Tato14 actually, do you mean to say simply restrict the attention to specific subset of tiles, without upsampling or changing the patch size? because that would be doable

**Comment by Tato14** [comment]
> @Tato14 actually, do you mean to say simply restrict the attention to specific subset of tiles, without upsampling or changing the patch size? because that would be doable

Yes, I guess it could be a great starting point. If you could force the model to learn for some specific regions using a mask, for example, this could be easily used when working with higher resolution.

**Comment by lucidrains** [comment]
@Tato14 Ok, I'll add the mask later today :) Yes, it's a great paper, maybe I'll implement it one day when I'm bored :)

**Comment by lucidrains** [comment]
https://github.com/lucidrains/vit-pytorch/releases/tag/0.0.4 done!

**Comment by Tato14** [comment]
> @Tato14 Ahh, I understand your problem. Very much related to https://arxiv.org/abs/1905.03711 and I believe it will work, but outside the scope of this repository.

[PyTorch implementation](https://github.com/sara-nl/attention-sampling-pytorch), linked on Paperswithcode new feature on arxiv
