### ISSUE TITLE
Whats the point of the class token here?

### ISSUE THREAD

**Issue by Manojbhat09** [lucidrains/vit-pytorch#20]
Really appreciate your work.
Question : As the topic.

**Comment by lucidrains** [comment]
@Manojbhat09 it's a common practice in NLP where you have one token that pools information from the rest of the tokens through rounds of attention, usually to classify the sentence at the end. whether it is completely necessary for ViT to work is up to debate

**Comment by Manojbhat09** [comment]
Thank you for your clear explanation. Hope others too find it helpful.

**Comment by zhongyy** [comment]
Thank you for the explaination !
