### ISSUE TITLE
Question about code of `vit_for_small_dataset.py`

### ISSUE THREAD

**Issue by RaymondJiangkw** [lucidrains/vit-pytorch#206]
Hi, 

Thanks for the outstanding efforts to bring ViT to the framework of PyTorch, which is meaningful for me to learn about it!

However, when I review the code in `vit_for_small_dataset.py`, in the `SPT`, I find code in the line `86` to be weird.

```python
patch_dim = patch_size * patch_size * 5 * channels
```

I fail to understand the meaning of `5` here. Is it a typo? Based on the context here, it seems that `patch_size * patch_size * channels` is more appropriate.

Thanks for your attention!

**Comment by lucidrains** [comment]
@RaymondJiangkw Hi Raymond! Not a typo! 5 accounts for the shifted feature map, which there are 4 (up left, up right, down left, down right) + the original unshifted

**Comment by RaymondJiangkw** [comment]
Hi,

Thanks for your response! I understand its meaning here :D I forget about the shifts.
