### ISSUE TITLE
CCT and non-square images

### ISSUE THREAD

**Issue by Gasp34** [lucidrains/vit-pytorch#208]
I think the actual implementation of CCT doesn't allow to pass non-square image.

If I pass `img_size` as a tuple I managed do it by changing these two lines https://github.com/lucidrains/vit-pytorch/blob/2aae406ce844e08da881befaeaab044b67d02898/vit_pytorch/cct.py#L327-L328 with

```
height=img_size[0],
width=img_size[1]),
 ```

Maybe you could modify the code in this repo in order that it works when `img_size` is an int or a tuple.

**Comment by lucidrains** [comment]
@Gasp34 oh yup, sure https://github.com/lucidrains/vit-pytorch/commit/9cd56ff29bb61849b823cd268b643c9febc53b95

**Comment by Gasp34** [comment]
thx a lot !
