### ISSUE TITLE
How to load the pretrain model

### ISSUE THREAD

**Issue by nooralahzadeh** [lucidrains/vit-pytorch#21]
Google released the model
How we can load them?

https://github.com/google-research/vision_transformer

**Comment by lucidrains** [comment]
@nooralahzadeh hmmm, I'm almost sure either @rwightman would do it, or @huggingface will make a grand entrance into the computer vision space. either way, I'll do it if they don't do it within a week :)

**Comment by rwightman** [comment]
@nooralahzadeh @lucidrains I'm hoping I have a chance to tackle this by early next week. A quick look at their model suggests it should be fairly quick to port their weights to either this one or my PyTorch impl. It should be a matter of reshaping and possibly concating some weights or conversely, splitting some linear layers.

**Comment by lucidrains** [comment]
@rwightman thank you for all your work in the CV space :D

**Comment by rwightman** [comment]
@lucidrains and likewise thank you re the attention work. Now that latest attention and transformer ideas are colliding with CV in a big way, it's great to have reliably correct, clean PyTorch impl of the latest ideas to compare against or borrow from :)

**Comment by lucidrains** [comment]
@nooralahzadeh released by Ross! https://github.com/rwightman/pytorch-image-models

**Comment by xybx6** [comment]
Did you find the pre-trained model?
