### ISSUE TITLE
MaxViT's MbConv doesn't match article.

### ISSUE THREAD

**Issue by arquolo** [lucidrains/vit-pytorch#223]
According to [article](https://arxiv.org/pdf/2204.01697.pdf), this block should be F -> 4 F -> F channel mapping, as authors use 4 for InvertedBottleneck's expansion.
But [here](https://github.com/lucidrains/vit-pytorch/blob/81661e3966629fd8dcf3d39839ff661ab2af19ce/vit_pytorch/max_vit.py#L103) `hidden_dim` is not used at all, and dim_in/dim_out are only used.
Given that you call this like `MBConv(layer_dim, layer_dim)`, you actually use 1 for effective expansion rate (i.e. no expansion), which is likely undesired.
Also, original article uses GELU activation instead of SiLU, but I don't know whether this should be fixed too.

It should be
```python
def MBConv(
    dim_in,
    dim_out,
    *,
    downsample,
    expansion_rate = 4,
    shrinkage_rate = 0.25,
    dropout = 0.
):
    hidden_dim = int(expansion_rate * dim_out)
    stride = 2 if downsample else 1

    net = nn.Sequential(
        nn.Conv2d(dim_in, hidden_dim, 1),
        nn.BatchNorm2d(hidden_dim),
        nn.GELU(),
        nn.Conv2d(hidden_dim, hidden_dim, 3, stride=stride, padding=1, groups=hidden_dim),
        nn.BatchNorm2d(hidden_dim),
        nn.GELU(),
        SqueezeExcitation(hidden_dim, shrinkage_rate=shrinkage_rate),
        nn.Conv2d(hidden_dim, dim_out, 1),
        nn.BatchNorm2d(dim_out),
    )

    if dim_in == dim_out and not downsample:
        net = MBConvResidual(net, dropout=dropout)

    return net
```

**Comment by lucidrains** [comment]
@arquolo Hi Paul and thank you for catching this error! https://github.com/lucidrains/vit-pytorch/commit/2c6dd7010af59a4e09c97104ccc54fca46eae42d
