### ISSUE TITLE
Question about example notebook

### ISSUE THREAD

**Issue by albusdemens** [lucidrains/vit-pytorch#229]
Hi, I have a question about the [example notebook](https://github.com/lucidrains/vit-pytorch/blob/main/examples/cats_and_dogs.ipynb): is the ViT model pretrained or do we start training from scratch? 

In case we start training from scratch, is there a way we can start with a pretrained model instead? Thanks!

**Comment by argosopentech** [comment]
The example notebook is training the model from scratch here:

```
    for data, label in tqdm(train_loader):
        data = data.to(device)
        label = label.to(device)

        output = model(data)
        loss = criterion(output, label)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
```
