### ISSUE TITLE
simplify `to_patch_embedding` using Conv2d

### ISSUE THREAD

**Issue by avihu111** [lucidrains/vit-pytorch#236]
Hi,
Thanks for this great repo!
I have a suggestion for a simpler implementation for `to_patch_embedding`. Instead of:
```
        self.to_patch_embedding = nn.Sequential(
            Rearrange('b c (h p1) (w p2) -> b (h w) (p1 p2 c)', p1 = patch_height, p2 = patch_width),
            nn.Linear(patch_dim, dim),
        )
```
one can use a Conv2d layer, with `patch_size` kernels, and with a `patch_size` stride:
```        
        self.to_patch_embedding = nn.Sequential(
            nn.Conv2d(in_channels=channels, out_channels=dim, kernel_size=patch_size, stride=patch_size),
            nn.Flatten(start_dim=2, end_dim=-1)
        )
```

This way, the extension for 3D vision transformers much simpler (just change to nn.Conv3D).

Thanks again!

**Comment by avihu111** [comment]
Link to relevant lines:
https://github.com/lucidrains/vit-pytorch/blob/4b8f5bc90002a5506d765c811b554760d8dd6ee7/vit_pytorch/vit.py#L94

**Comment by avihu111** [comment]
It also requires to add a transpose in the forward pass
```
        x = self.to_patch_embedding(img).transpose(1, 2)
```

**Comment by Ahwow** [comment]
Wonderful suggestion！

**Comment by Ahwow** [comment]
Wonderful suggestion！

**Comment by lucidrains** [comment]
@avihu111 ohh nice, yea, i think its a matter of preference. personally prefer einops better when there is no overlapping

let me know if https://github.com/lucidrains/vit-pytorch#3d-vit helps
