### ISSUE TITLE
How to use mask in ViT

### ISSUE THREAD

**Issue by bigMaxM** [lucidrains/vit-pytorch#246]
Hey guys, the size of my images is variant, so I pad those smaller images and I need to use masks to ignore these padding in ViT. However, it seems current ViT does not provide masks to do so. So does it mean I cannot use masks in ViT now? It will be very grateful if anyone can give some suggestion!

**Comment by lucidrains** [comment]
@bigMaxM are your image dimensions at a multiple of the patch size? i can share a gist of vit later today (with masking) if you need it. probably too unusual to include in the repository alone

**Comment by lucidrains** [comment]
@bigMaxM let me know if [this](https://gist.github.com/lucidrains/5193d38d1d889681dd42feb847f1f6da) works

**Comment by bigMaxM** [comment]
Thanks for your reply! There are still some problems but I am trying.
