### ISSUE TITLE
Use on 1-Dimensional data

### ISSUE THREAD

**Issue by shivam-chandhok** [lucidrains/vit-pytorch#27]
Thank you very much for your code.
I was wondering if we could use the model on data of shape 1x512x2 (HxWxC)
What changes can we make in the code to make it compatible with such data dimensions?

**Comment by lucidrains** [comment]
@shivam-chandhok hey! if you really want it to be similar to the crude method used in this paper, you would do

```python
i = torch.randn(1, 1, 512, 2)

patch_size = 16
model_dim = 512
patches = rearrange(i, 'b h (p w) c -> b (h w) (p c)')

to_features = nn.Linear(2 * patch_size, model_dim)
features = to_features(patches)
transformer(features)
```

or something like that
