### ISSUE TITLE
Potential regression with PT 2.0 and CUDA 12.2/CuDNN 8.9.4

### ISSUE THREAD

**Issue by roywei** [lucidrains/vit-pytorch#281]
Hi we are benchmarking ViT on H100 GPUs but found it's slower with newer CUDA/CUDNN recommended by Nvidia.

PyTorch version: 2.0.1 
model config: default (large)
datatype: bf16

### CUDA 12.2 + CUDNN 8.9.4 , avg throughput: 94.95987583, 3 runs:
"throughput": 95.0631667348959
"throughput": 94.94235140772204
"throughput": 94.87410935279841

### CUDA 11.8 + CUDNN 8.9.2 , avg throughput: 106.193065, 3 runs:
"throughput": 106.35817540604774
"throughput": 106.06269191571305
"throughput": 106.15832773232279

This is unexpected, is there some potential regression on vanilla implementation of attention? we do see speed up on other language models using flash-attention or xformers. Any insights will be helpful, thanks!!

**Comment by lucidrains** [comment]
@roywei think you should take this up with the pytorch team
