### ISSUE TITLE
Question regarding 1d fft use

### ISSUE THREAD

**Issue by chengengliu** [lucidrains/vit-pytorch#292]
Hi, thanks so much for your excellent work! I just have one question regarding your last commit of simple_vit_with_fft: 
https://github.com/lucidrains/vit-pytorch/blob/d446a41243c91a43adcac6f0559d53f1a4eea4fa/vit_pytorch/simple_vit_with_fft.py#L131
In this commit you use a 1D fft; may I ask why not use torch.fft.fft2()? Since you are applying fft to img with size of (B,C,H,W) not (B,N,C). Thanks!

**Comment by lucidrains** [comment]
@chengengliu oops, for some reason thought fft would auto-infer 1d or 2d based on the shape

thanks!
