### ISSUE TITLE
Add implementation of LongVit

### ISSUE THREAD

**Issue by jpfeil** [lucidrains/vit-pytorch#297]
Wondering if you have any plans to include the recent LongVit model?

https://arxiv.org/abs/2312.03558

**Comment by lucidrains** [comment]
@jpfeil btw, thinking about a trip to Santa Cruz soon in March

**Comment by jpfeil** [comment]
Hey @lucidrains! Yes, it is implemented there, but I was wondering if it could be applied here using your flexible framework. I'd also like to apply the other methods here to gigapixel size images.

**Comment by lucidrains** [comment]
@jpfeil oh what framework were you thinking of using? do you mean the self supervised learning wrappers? i think it should work with their implementation (which is based on timm)

**Comment by jpfeil** [comment]
Okay, let me give it a try. Thanks for clarifying.
