### ISSUE TITLE
How to load pretrained weights

### ISSUE THREAD

**Issue by rbunn80110** [lucidrains/vit-pytorch#30]
I have downloaded the pretrained weights from https://github.com/rwightman/pytorch-image-models/releases/tag/v0.1-vitjx
However, I'm not sure how you load the weights into your cats and dogs example.  Anyone have a working example how to do this?

**Comment by lucidrains** [comment]
@rbunn80110 Hi Robert! You can just use Ross' comprehensive image library with https://rwightman.github.io/pytorch-image-models/
