### ISSUE TITLE
Whether to include pre-trained models

### ISSUE THREAD

**Issue by KawaiiAsh** [lucidrains/vit-pytorch#307]
Thanks for such a great job

does the repository include pre-trained models, which I am not seeing at the moment, or should I set up my own dataset to start training based on the implemented code?

**Comment by suryajayaraman** [comment]
Hi @KawaiiAsh , were you able to find pretrained weights for the implementation in this repo? Or are we to look into https://github.com/rwightman/pytorch-image-models
