### ISSUE TITLE
why only first vector is sufficient for classification

### ISSUE THREAD

**Issue by besaman** [lucidrains/vit-pytorch#33]
Thank you very much for sharing this great code.
I wonder why only the [first vector](https://github.com/lucidrains/vit-pytorch/blob/f1deb5fb7e7606dcb1d648f6e22c5f0631dce0e4/vit_pytorch/vit_pytorch.py#L126)  is sufficient for classifying the data (referred in paper as z0). I checked the paper, but it was not clear also.
Besides, as mentioned in [this issue](https://github.com/lucidrains/vit-pytorch/issues/29), the other vectors are useless and not representative.
Can you suggest any explanation?

**Comment by lucidrains** [comment]
@besaman it's just become a convention in NLP, the tradition was set by the very first BERT paper, which used the CLS (classify) token as a reserved token for predicting the sentence order. the rest of the tokens were used for denoising autoencoding

**Comment by lucidrains** [comment]
@besaman you can train it with other tokens and i'm almost sure there will be no difference. the key ingredient is Attention. That's all you need

**Comment by besaman** [comment]
> @besaman you can train it with other tokens and i'm almost sure there will be no difference. the key ingredient is Attention. That's all you need

Actually I did, but the results are much worse.
The only other thing that worked is the mean of them all.

**Comment by lucidrains** [comment]
Yeah, people typically sum or average them together

**Comment by lucidrains** [comment]
@besaman https://stackoverflow.com/questions/62705268/why-bert-transformer-uses-cls-token-for-classification-instead-of-average-over probably explains it better than i did
