### ISSUE TITLE
RegionViT - Local token embedding

### ISSUE THREAD

**Issue by minhquoc0712** [lucidrains/vit-pytorch#330]
Hi,

I believe there is an error here. In LayerNorm, the dimension of `LayerNorm`  should either be the number of channels `C` (which requires change the input to a channel-last format), or it should be [C, H, W] to normalize across the channels and spatial dimensions.

https://github.com/lucidrains/vit-pytorch/blob/fcb9501cdd9e056dd040915deb3e0a6378821843/vit_pytorch/regionvit.py#L212-L221

**Comment by lucidrains** [comment]
@minhquoc0712 ah, good catch

thank you Quoc!
