### ISSUE TITLE
Purpose of nn.Identity() in the ViT class

### ISSUE THREAD

**Issue by rish-16** [lucidrains/vit-pytorch#46]
Hey! 

Awesome project :)  Not really an issue, more of a question. Referring to this snippet:

```python
self.to_cls_token = nn.Identity()

...

x = self.transformer(x, mask)
x = self.to_cls_token(x[:, 0])
return self.mlp_head(x)
```

Can I please know what's the purpose of the `nn.Identity()` in the `ViT` class? As an identity transformation/matrix, it doesn't really change the incoming `x` value from the `Transformer()`, right?

What effect does it have in terms of changing the inputs passed into the MLP Head? 

Any help appreciated! 
 
Thanks :D

**Comment by lucidrains** [comment]
Hello! :D

I did that so I could use the name of that module as the hidden layer for BYOL self supervised learning! https://github.com/lucidrains/vit-pytorch#research-ideas you are right it isn't needed if you don't use BYOL at all

**Comment by rish-16** [comment]
Ah, I see! Thanks for the clarification :)
