### ISSUE TITLE
About computing num_patches 

### ISSUE THREAD

**Issue by aqibsaeed** [lucidrains/vit-pytorch#50]
Hi Phil,

Thank you for the nice implementation.

Could you please clarify why `()**2` is used in computing number of patches and patch_dim? 
https://github.com/lucidrains/vit-pytorch/blob/ea0924ec9632922dde0d4fdaa887d4f2bee3486f/vit_pytorch/vit_pytorch.py#L90

**Comment by lucidrains** [comment]
@aqibsaeed Hello! So I assume a square image, so imagine you have a 16 x 16 px image, and the patch size if 4 px, then along one dimension, you would have 4 patches. 4 ** 2 would give you 16 patches total

**Comment by aqibsaeed** [comment]
got it! it is only applicable for 2D input, right?

**Comment by lucidrains** [comment]
@aqibsaeed yes! for 1D, you would remove the ** 2 :)

**Comment by aqibsaeed** [comment]
awesome! thanks
