### ISSUE TITLE
How to run this model on linear data?

### ISSUE THREAD

**Issue by purbayankar** [lucidrains/vit-pytorch#52]
How to run this model on image features rather than image data like image features generated from pretrained ResNet?

**Comment by lucidrains** [comment]
@purbayankar I would recommend using https://github.com/lucidrains/axial-attention

**Comment by purbayankar** [comment]
@lucidrains Thank you very much for your solution. But my input to the model is of shape [2000,2048]. 2000 is my batch size and 2048 is the ResNet features/embeddings dimension. The number of classes to predict is 50. Can you please help me how to use visual transformer in this case?

**Comment by lucidrains** [comment]
@purbayankar If you want to use attention, you can't flatten the feature map yet. ex. the output would be something like [2000, 32, 8, 8], you would rearrange that to [2000, 64, 32] -> transformer. Or you can also rearrange to [2000, 8, 8, 32] -> axial transformer.

**Comment by lucidrains** [comment]
@purbayankar in either case, you won't be using vision transformer, if you are looking for a hybrid between resnet and attention. vision transformer is for pure attention solution.

**Comment by purbayankar** [comment]
@lucidrains Thank you very much for your solution. But in the paper An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale (https://arxiv.org/pdf/2010.11929.pdf), the following is written which I mark in red for your convenience.
![Screenshot (2)](https://user-images.githubusercontent.com/53092711/103178203-be55d800-48a6-11eb-8939-090af567324e.png)
My question is how to implement this feature mentioned in the Hybrid architecture section.

**Comment by lucidrains** [comment]
@purbayankar you can follow the example here https://github.com/lucidrains/reformer-pytorch#examples the code under "image -> caption"

**Comment by lucidrains** [comment]
@purbayankar you can use any of my implementations in place of the Reformer, I recommend starting with full attention https://github.com/lucidrains/x-transformers

**Comment by purbayankar** [comment]
@lucidrains Can https://github.com/lucidrains/axial-attention or https://github.com/lucidrains/x-transformers be used for classification task like Vision Transformer?

**Comment by lucidrains** [comment]
@purbayankar yea! they are just missing the MLP head
