### ISSUE TITLE
Problem with ResNet

### ISSUE THREAD

**Issue by doglab753** [lucidrains/vit-pytorch#54]
Hi! I would like to train Vit using distiller in a dataset with grayscale images, but I am having problems with the ResNet since it is expecting inputs with 3 channels and my images have only 1. Do you have any suggestions? Thanks!

This is the error:

`RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[64, 1, 224, 224] to have 3 channels, but got 1 channels instead`

**Comment by lucidrains** [comment]
Hey! You'll either have to train your own, find a model that accepts greyscale, or expand your greyscale image to RGB `img.expand(-1, 3, -1, -1)`

**Comment by doglab753** [comment]
Thanks!
