### ISSUE TITLE
Image retrieval / similarity 

### ISSUE THREAD

**Issue by johnyquest7** [lucidrains/vit-pytorch#6]
Thanks for this great resource.
Planning to play with your cats and dog example. 
I am wondering whether this approach could be used for image retrieval / image similarity?
Have you looked into it?

**Comment by lucidrains** [comment]
@johnyquest7 hey Johnson! yea absolutely! It works like any other neural net. You can take the embedding (usually the output at the very last attention layer) https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/vit_pytorch.py#L113 and use your favorite nearest neighbor library (for example, Faiss https://github.com/facebookresearch/faiss) and you've got yourself retrieval

**Comment by bongoramondo** [comment]
I found this question, but I do not want to open a new issue. @lucidrains  For the retrieval, shouldn't we take the output of the last attention layer, but more specifically, the class-token output? 
``` 
    x = self.transformer(x, mask)
    x = x[:, 0]        <- these are the embeddings we are interesed in
```
