### ISSUE TITLE
Support for non-square images

### ISSUE THREAD

**Issue by Laserbear** [lucidrains/vit-pytorch#61]
I would like to use this with an image of size 640 by 480. Does the library support non-square images? If not, would it be a simple fix? I would be happy to make a PR if it's not likely to be a breaking change.

**Comment by lucidrains** [comment]
@Laserbear it works by default! you just have to make sure your height and width (640 and 480) are divisible by the patch size! let attention figure the rest out (regarding patch positions)

**Comment by niclaswue** [comment]
Great, thank you! This could maybe be included in the readme, as most datasets won't have square images.

**Comment by lucidrains** [comment]
@niclaswue ok done!
