### ISSUE TITLE
Doubts on training the distilled ViT

### ISSUE THREAD

**Issue by Abhranta** [lucidrains/vit-pytorch#62]
How to get the model outputs in case of training the distilled ViT ?The readme doesn't give sufficient information about this. Can someone give a snippet of a typical training loop for classification using this  ?

**Comment by lucidrains** [comment]
@Abhranta you just have to run `distill_vit_instance.to_vit()` and you'll have the usual ViT instance to work and do prediction off of

**Comment by lucidrains** [comment]
@Abhranta I actually made it to if you kept around the `DistillableVit` instance, you can still use that to run predictions
