### ISSUE TITLE
doubt about scale in Attantion

### ISSUE THREAD

**Issue by urkax** [lucidrains/vit-pytorch#65]
line 41 in vit_pytorch.py: self.scale = dim ** -0.5
I think self.scale should be dim_head ** -0.5
As is mentioned in _Attention is All you Need_ , dk should be the dimension of queries and keys.
Correct me if I am wrong, thanks in advance

**Comment by lucidrains** [comment]
@urkax oh man, this was my mistake, thank you for catching this! fixed in the latest!

**Comment by lucidrains** [comment]
i've been coding Attention for nearly a year now and still making rookie mistakes 🙏 https://github.com/lucidrains/vit-pytorch/commit/85314cf0b6c4ab254fed4257d2ed069cf4f8f377
