### ISSUE TITLE
Adding pos embedding

### ISSUE THREAD

**Issue by shabie** [lucidrains/vit-pytorch#70]
The following line in the code `vit_pytorch.py`:

        x += self.pos_embedding[:, :(n + 1)]

Is the part with `[:, :(n + 1)]` necessary? If yes, how so?

**Comment by lucidrains** [comment]
@shabie It isn't necessary if you were to be passing in the same sized image every time. Someone brought up that they needed to pass in images of different sizes (but with height and width divisible by the patch size). This naively allows for that

**Comment by shabie** [comment]
Thank you for your prompt reply. Does this mean that it sort of like "ignores" the extra patches by considering the first `(n + 1)` onyl?

Side note: Amazing repo BTW.

**Comment by lucidrains** [comment]
@shabie yup, that's right! it's just like how we do language model learning!
