### ISSUE TITLE
Masking doesn't work with batches?

### ISSUE THREAD

**Issue by AmitMY** [lucidrains/vit-pytorch#71]
I took the example in the README, and changed the `img` to be of batch 2

from vit_pytorch import ViT

```python
v = ViT(...)

img = torch.randn(2, 3, 256, 256)
mask = torch.ones(2, 8, 8).bool() # optional mask, designating which patch to attend to

v(img, mask = mask) # (2, 1000)
```

This yields the following error:
> RuntimeError: The size of tensor a (16) must match the size of tensor b (2) at non-singleton dimension 1

Which I believe is because of the mask not being replicated on the number of heads? but I'm not sure.

A more simple reproduction of the relevant element is:
```python
from vit_pytorch.vit_pytorch import Transformer
import torch

transformer = Transformer(dim=128, depth=1, heads=4, dim_head=32, mlp_dim=128, dropout=0.4)

# Batch of 10 sequences of 64 tokens + CLS
x = torch.ones((10,64 + 1,128), dtype=torch.float)

# Batch of 10 masks of length 64
mask = torch.ones((10, 64), dtype=torch.bool)

transformer(x, mask=mask)
```

[Google Colab for repruction](https://colab.research.google.com/drive/1yUtYNrSD_1aeZ5neeuvZpwBHeJv-OidF?usp=sharing)

**Comment by lucidrains** [comment]
@AmitMY Thank you for catching this! Indeed I left the heads to be implicitly broadcasted, but you run into edge cases that way https://github.com/lucidrains/vit-pytorch/commit/3f2cbc6e23b935224b57915a2b0e1a21eb60c5a6#diff-fce7f92e0b957764a240f657482514430a2fcdd8a0fcfc1d23372f119a92e6ccR60

**Comment by AmitMY** [comment]
Works as expected. Thanks for the swift reply!
