### ISSUE TITLE
git clone not working with jupyter notebook

### ISSUE THREAD

**Issue by lessw2020** [lucidrains/vit-pytorch#8]
Very happy to see transformers moving further into vision and big thanks for this repo!

I wanted to point out that git clone isn't working properly for this repo due to some issue with the new .ipynb notebook:

> C:\Users\lessw>git clone https://github.com/lucidrains/vit-pytorch.git vit2
Cloning into 'vit2'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 94 (delta 53), reused 48 (delta 18), pack-reused 0
Unpacking objects: 100% (94/94), done.
error: unable to create file examples/VisualTransformer | Cats&Dogs Edition.ipynb: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

I hit this yesterday as well and it further complicated any git pulls to sync to latest updates. (hence trying now with vit2)

**Comment by lucidrains** [comment]
@lessw2020 i've updated the ipynb filename in the latest commit, could you try again?

btw, thanks for all your open source optimizer work :)

**Comment by lessw2020** [comment]
Hi @lucidrains  - thanks for the fast update!  Working great now:

> C:\Users\lessw>git clone https://github.com/lucidrains/vit-pytorch.git vit2
Cloning into 'vit2'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (97/97), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 97 (delta 54), reused 51 (delta 19), pack-reused 0
Unpacking objects: 100% (97/97), done.

re: optimizers - thanks for the kind words!  I am hoping to test out adahessian btw with vit here as it's produced good results on transformers for nlp and may be ideal for vit as well (although with much higher gpu mem requirements to use).

Thanks again for making this repo and hope to be able to contribute as I work more with ViT!
