### ISSUE TITLE
T2TViT 1-dimensional data

### ISSUE THREAD

**Issue by aslarsen** [lucidrains/vit-pytorch#80]
Hi all, I want to use the T2TViT version on 1-dimensional data where I previously have used a 1D-CNN. This is easy with the standard transformer in this repository, but I can’t get it to work with the T2TViT. The pytorch operation unfold does not seem to support 1-dimensional data. Is there any way around this?

**Comment by lucidrains** [comment]
Hey! You could try treating your 1 dimensional data as 2d and just have the kernel size of that dimension be 1 when unfolding

Does that work?

**Comment by aslarsen** [comment]
That worked thanks :)
