### ISSUE TITLE
Regression on stacked images

### ISSUE THREAD

**Issue by surajmahangade** [lucidrains/vit-pytorch#81]
I want to perform regression by stacking 2 images, I was a bit confused on how to do it. Any help is appreciated.
Thank you.

**Comment by lucidrains** [comment]
Oh, what do you mean by stacking 2 images?

**Comment by surajmahangade** [comment]
I have a sequence of images, so I will be stacking 2 images at a time.

**Comment by lucidrains** [comment]
@surajmahangade ohh ok! you'll want to use https://github.com/lucidrains/TimeSformer-pytorch

**Comment by surajmahangade** [comment]
Thank you for your quick response.
Where should I change to use it for regression?
Because here I see only the Linear layer.
https://github.com/lucidrains/TimeSformer-pytorch/blob/6b85a5e22632ed51f900e646f8355f2d2756b4cb/timesformer_pytorch/timesformer_pytorch.py#L141

**Comment by lucidrains** [comment]
@surajmahangade you can just set `num_classes = 1`

**Comment by surajmahangade** [comment]
Thank you.
Really great work done.

**Comment by raijinspecial** [comment]
> @surajmahangade you can just set `num_classes = 1`

I have a slightly different question on regression, let’s say that the input is a video clip and for output I want a single float value per frame. 

I have tried setting the number of classes equal to the number of input frames which does not seem to work at all and feels a little weird. In contrast a 3DCNN with no linear layers can learn this task pretty well. Interested in your thoughts. 
Thanks!

**Comment by surajmahangade** [comment]
What you can do is, use a sliding window. Let's say you have 10 frames, then take frames [1,2,3] and get the regression output for the third frame, then go for frame [2,3,4] and get regression output for the 4th frame. This way you will miss the regression output for the first 2 frames, the rest should be fine.

By the way, I also have a doubt @lucidrains, if I want to predict let's say 3 regression outputs instead of 1, I can keep numclasses=3? This way for one video I get 3 regression output right?
Thank you.
