### ISSUE TITLE
Get Attention Weights

### ISSUE THREAD

**Issue by joellehanna97** [lucidrains/vit-pytorch#82]
Hi, is there an easy way to get/extract the attention weights in order to visualise the attention map ?

Thanks !

**Comment by lucidrains** [comment]
@joellehanna97 Hi Joelle, let me know if https://github.com/lucidrains/vit-pytorch#accessing-attention works for you

**Comment by joellehanna97** [comment]
> @joellehanna97 Hi Joelle, let me know if https://github.com/lucidrains/vit-pytorch#accessing-attention works for you

It works thanks !

**Comment by givkashi** [comment]
> > @joellehanna97 Hi Joelle, let me know if https://github.com/lucidrains/vit-pytorch#accessing-attention works for you
> 
> It works thanks !

Hi, How did you visualize attention map?
