### ISSUE TITLE
Should this be `extend` instead of `append`? 

### ISSUE THREAD

**Issue by ovshake** [lucidrains/vit-pytorch#85]
https://github.com/lucidrains/vit-pytorch/blob/3a3038c7021b5a1e1afa676653b2219b6433d6e0/vit_pytorch/vit.py#L64

**Comment by lucidrains** [comment]
ohh, you could do that it that way, but it'd be more aptly named `self.modules` and you lose where layers begin and end

**Comment by lucidrains** [comment]
@ovshake i keep it that way since in transformers, you also have cross attention modules, so each layer could have 2 or 3 modules

**Comment by lucidrains** [comment]
@ovshake sometimes there are depth dependent logic too, so it's better this way

**Comment by ovshake** [comment]
Oh I see, I didn't think of that, thanks for the clarification 👍
