### ISSUE TITLE
about cvt?

### ISSUE THREAD

**Issue by huixiancheng** [lucidrains/vit-pytorch#95]
check that, the dim_head of stage 3 is 4 not 6 ?

https://github.com/lucidrains/vit-pytorch/blob/bad4b94e7b4baa544ca36149431f7912eccd4b49/vit_pytorch/cvt.py#L107-L137

Look like the default set is cvt13 
![QQ截图20210427111453](https://user-images.githubusercontent.com/65054204/116179380-d1d85900-a749-11eb-9a41-e20d722f63c1.png)

**Comment by huixiancheng** [comment]
Moreover, what's the meaning of proj_kernel? 
Look like we should replace the 3 in DepthWiseConv2d to proj_kernel? Is it right?

https://github.com/lucidrains/vit-pytorch/blob/bad4b94e7b4baa544ca36149431f7912eccd4b49/vit_pytorch/cvt.py#L60-L78

**Comment by lucidrains** [comment]
@huixiancheng yes, you are right on both accounts https://github.com/lucidrains/vit-pytorch/commit/54af2209306d3d1c9fa1c9e2974b4dd93bac684f :pray:

**Comment by huixiancheng** [comment]
Thank you for your code. :bow:

**Comment by huixiancheng** [comment]
Hi Dear @lucidrains  
Do your think we need LN between Patch embedding and Transfomer blocks?
https://github.com/lucidrains/vit-pytorch/blob/bad4b94e7b4baa544ca36149431f7912eccd4b49/vit_pytorch/cvt.py#L147-L150
The orginal show they: rearrange BCHW to  B(HW)C then with a LN.
![QQ截图20210427154027](https://user-images.githubusercontent.com/65054204/116204306-3e198380-a76f-11eb-8bd8-08806947c2c5.png)
I think flattened is not necessary like your code show. Since we will rearrange it back again in DepthWiseConv2d. 
But look like LN is necessary at least for 1st stage. Maybe it's not need for stage 2 or 3.
However, I have no idea of the important of LN to Transformer

**Comment by lucidrains** [comment]
@huixiancheng i missed this detail! do you want to look at https://github.com/lucidrains/vit-pytorch/commit/3df6c31c612ab0261fe3a5f8dd39b7957f5b2a56 and see if that fits your needs? I also brought in a layernorm that works on the first dimension, so to avoid all the reshapes and flattening

**Comment by huixiancheng** [comment]
thx!   Nice work!
