### ISSUE TITLE
About the vit pos embedding

### ISSUE THREAD

**Issue by ShiMinghao0208** [lucidrains/vit-pytorch#98]
where the sin and cos embedding？

**Comment by lucidrains** [comment]
Vit doesnt use sinusoidal embeddings - they chose to use a learned absolute positional embedding

**Comment by ShiMinghao0208** [comment]
> Vit doesnt use sinusoidal embeddings - they chose to use a learned absolute positional embedding

ok，thank u

**Comment by henbucuoshanghai** [comment]
Vit doesnt use sinusoidal embeddings - they chose to use a learned absolute positional embedding?
the paper said it?where?   tks
